//All Rights Reserved.
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// XML Revision      : $Revision: 1.238 $
//
//---------------------------------------------------------------------------------------------------------------
//
//  ahbbus22 hierarchy
//
//  ahbbus22
//
// DESCRIPTION: 2 master, 2 slave AHB channel, with all Logical Directions Allowed for the clock and reset of the mirrored slave ports
//


module ahbbus22
    #( parameter
    start_addr_slv0_mirror = "0x00000000",
    restart_addr_slv0_mirror = "0x00000000",
    start_addr_slv0 = "($start_addr_slv0_mirror ) / 65536",        //EXAMPLE TO SHOW, HOW TO WRITE PARAMETERES.
    restart_addr_slv0 = "($restart_addr_slv0_mirror ) / 65536",
    range_slv0 = "$range_slv0_mirror",
    split_slv0 = TRUE,
    mst_access_slv0 = 3,
    start_addr_slv1 = "$start_addr_slv1_mirror/65536",
    restart_addr_slv1 = "$restart_addr_slv1_mirror/65536",
    range_slv1 = "$range_slv1_mirror",
    split_slv1 = FALSE,
    mst_access_slv1 = 3,
    defmast = 1
    )
    
    (
    input rst,
    input remap,        //
    input clk,
    output hgrant_mst0,
    output hready_mst0,
    output [1:0] hresp_mst0,
    output [31:0] hrdata_mst0,
    output hgrant_mst1,
    output hready_mst1,
    output [1:0] hresp_mst1,
    output [31:0] hrdata_mst1,
    input hbusreq_mst0,        //
    input hlock_mst0,
    input [1:0] htrans_mst0,
    input [31:0] haddr_mst0,
    input hwrite_mst0,
    input [2:0] hsize_mst0,
    input [2:0] hburst_mst0,
    input [3:0] hprot_mst0,
    input [31:0] hwdata_mst0,
    input hbusreq_mst1,        //
    input hlock_mst1,
    input [1:0] htrans_mst1,
    input [31:0] haddr_mst1,
    input hwrite_mst1,
    input [2:0] hsize_mst1,
    input [2:0] hburst_mst1,
    input [3:0] hprot_mst1,
    input [31:0] hwdata_mst1,
    output hsel_slv0,
    output [31:0] haddr_slv0,
    output hwrite_slv0,
    output [1:0] htrans_slv0,
    output [2:0] hsize_slv0,
    output [2:0] hburst_slv0,
    output [31:0] hwdata_slv0,
    output [3:0] hprot_slv0,
    output hreadyin_slv0,
    output [3:0] hmaster_slv0,
    output hmastlock_slv0,
    input hreadyout_slv0,        //
    input [1:0] hresp_slv0,        //
    input [31:0] hrdata_slv0,        //
    input [15:0] hsplit_slv0,        //
    output hsel_slv1,
    output [31:0] haddr_slv1,
    output hwrite_slv1,
    output [1:0] htrans_slv1,
    output [2:0] hsize_slv1,
    output [2:0] hburst_slv1,
    output [31:0] hwdata_slv1,
    output [3:0] hprot_slv1,
    output hreadyin_slv1,
    output [3:0] hmaster_slv1,
    output hmastlock_slv1,
    input hreadyout_slv1,        //
    input [1:0] hresp_slv1,        //
    input [31:0] hrdata_slv1,        //
    input [15:0] hsplit_slv1        //
    
    );
    
    
endmodule

